### ISSUE TITLE
Tick: Code Refactor

### ISSUE THREAD

**Issue by ControlCplusControlV** [ControlCplusControlV/Scribe#35]
### Tasks
- [ ] Break tests out of `milestone_1` and comment out tests in `milestone_2` before breaking out
- [ ] Change repo structure to `crates` and `bin` (bin should be repl and `.yul` transpiler, everything else in a crate)
- [ ] Integrate repl (likely just import from miden repo and use that)
- [ ] Clippy + Cargo fmt in CI and enforced
- [ ] Yul Parsing investigation and plan
- [ ] Upgrade to Miden 0.3
