### ISSUE TITLE
Tock : New Features

### ISSUE THREAD

**Issue by ControlCplusControlV** [ControlCplusControlV/Scribe#43]
### Tasks
- [ ] For Loop to Repeat Statement
- [ ] Constant Folding
- [ ] Common subexpression elimination
- [ ] Lifetime Management
- [ ] Dynamic re-ordering of vars to optimize stack usage
- [ ] Cost estimation
- [ ] One-time stack re-ordering step for repeat loops
- [ ] Before expensive loops, push stack vars to memory
- [ ] MLOAD/MSTORE Separation
